### ISSUE TITLE
Add more Rise versions (JARs)

### ISSUE THREAD

**Issue by Coccocoahelper** [WonderlandLibrary/wonderlandlibrary#8]
I keep doing this… In here, you'll find most of the cracks: https://github.com/VuDungVapeV4/MCCLoader-Free/blob/d9ecf5802c086e62180e2e5696d25bf958b3472b/Rise

**Comment by jezevcik** [comment]
Learn how to use pull requests

**Comment by funnius** [comment]
> Learn how to use pull requests

lmao
